version: "3"

services:
  python:
    build: .
    image: "python-redis:snippets"
    container_name: "python-redis-snippets"
    tty: true
    volumes:
      - ".:/usr/src/app"
    network_mode: "host"

  redis:
    image: "redis:latest"
    container_name: "redis-python"
    ports:
      - "6379:6379"
    network_mode: "host"
